### ISSUE TITLE
Submitter is null when clicked

### ISSUE THREAD

**Issue by rjm-codes** [ry0id/smol-gravatar-app#6]
Whenever I click the 'submitter' input box to submit the form, it returns null and/or undefined. If anyone has any idea why and can assist me in fixing it, make a pull request or contact me on Discord or Twitter. 

Twitter - [@binaryvoid](https://twitter.com/binaryvoid) 
Discord - void#0001

**Comment by Nevvulo** [comment]
The `submitter` input box is being called before it's created in the HTML body. Run the script after the DOM has loaded, or after the element has been created and it should work fine.
